### ISSUE TITLE
Deploy OSS CRM

### ISSUE THREAD

**Issue by dlapiduz** [18F/cg-skyporter#1]
In order to have a lead tracking solution we should have a CRM for cloud.gov.

**Acceptance Criteria**:

- [x] There is an app that can track the status of sales leads and existing customers
- [x] The app can be customized to track in what instance of the process they are
- [ ] The app integrates with UAA auth (optional)

**Implementation Ideas**:

Deploy either suitecrm.com or fatfreecrm.com

**Comment by berndverst** [comment]
suitecrm.com deployed at crm.fr.cloud.gov

Code here: https://github.com/18F/cf-example-suitecrm

**Comment by berndverst** [comment]
Suite CRM supports SAML. Would need some rewriting to use https://github.com/cloudfoundry/uaa

**Comment by mogul** [comment]
> Suite CRM supports SAML. Would need some rewriting to use https://github.com/cloudfoundry/uaa

Why's that? UAA is also a SAML provider.

**Comment by mogul** [comment]
Update: We're planning to move to Salesforce with the Agency Partnerships crew, so won't be maintaining this.
